# Generated by Django 5.1.1 on 2024-09-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
